name: aviancataxi
description: "proyecto 3 parcial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #firebase_auth: ^4.11.3  # Para autenticación
  #firebase_core: ^2.18.0  # Core de Firebase
 #cloud_firestore: ^4.15.1 # Para la base de datos (HU-02)
 # intl: ^0.17.0
  firebase_core: ^2.32.0         # usa la versión más reciente declarada
  firebase_auth: ^4.16.0         # usa la más reciente también
  cloud_firestore: ^4.17.5       # misma lógica, usa la más reciente
  intl: ^0.17.0
                                # Para formateo de fechas
  excel: ^2.1.0              # Para crear archivos Excel
  permission_handler: ^11.0.1 # Para permisos de almacenamiento
  path_provider: ^2.1.1      # Para obtener rutas del sistema
  open_file: ^3.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true