name: aviancataxi
description: "proyecto 3 parcial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  excel: ^4.0.2
  path_provider: ^2.1.3
  open_filex: ^4.5.0

  firebase_core: ^2.32.0         # usa la versión más reciente declarada
  firebase_auth: ^4.16.0         # usa la más reciente también
  cloud_firestore: ^4.17.5       # misma lógica, usa la más reciente
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
